github.com:
    user: connor15mcc
    git_protocol: ssh
    users:
        connor15mcc:
    oauth_token: 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
github.coecis.cornell.edu:
    oauth_token: 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
    user: cjm365
    git_protocol: ssh
