[font]
size = 18

[font.normal]
family = "Fira Code"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[general]
import = ["~/.config/alacritty/themes/themes/kanagawa_dragon.yaml"]
