[user]
name = "Connor McCarthy"
email = "connor15mcc@gmail.com"

[ui]
default-command = ["log", "--limit=3"]
pager = "delta"
diff.format = "git"

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

# To prevent rewriting commits authored by other users:
[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"


[template-aliases]
# Show unique prefix and the rest surrounded by brackets
'format_short_id(id)' = 'id.shortest(12).prefix() ++ "[" ++ id.shortest(12).rest() ++ "]"'
# Show username (rather than email)
'format_short_signature(signature)' = 'signature.email().local()'
default_commit_description = '''
"

Closes #NNNN
"
'''

[git]
push-bookmark-prefix = "connor15mcc/"
